#spring.application.name=daily-haul
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test
#spring.jpa.show-sql=true
#spring.jpa.hibernate.ddl-auto=update
#management.endpoints.web.exposure.include=*

spring:
  application:
    name: daily-haul
  h2:
    console:
      enable: true
  datasource:
    url: jdbc:h2:mem:test
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

management:
  endpoints:
    web:
      exposure:
        include: beans, health
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always