spring:
  application:
    name: daily-haul
  datasource:
    url: jdbc:postgresql://localhost:5432/daily-haul
    username: costigan
    password: billyjr
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: beans, health
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always